name: build
on: 
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Login to Docker Hub
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build amd64 image
      run: |
        docker build -f src/main/docker/Dockerfile.amd64 -t manorrock/jenkins:amd64-snapshot .
        docker push manorrock/jenkins:amd64-snapshot
    - name: Push Docker manifest
      run: |
        export DOCKER_CLI_EXPERIMENTAL=enabled
        docker manifest create manorrock/jenkins:snapshot \
          manorrock/jenkins:amd64-snapshot
        docker manifest annotate manorrock/jenkins:snapshot \
          manorrock/jenkins:amd64-snapshot --os linux --arch amd64
        docker manifest push manorrock/jenkins:snapshot
